/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphical_user_interface;

/**
 *
 * @author zofia
 */
public class PrincipalPanel extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalPanel
     */
    public PrincipalPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newItem = new javax.swing.JMenuItem();
        openItem = new javax.swing.JMenuItem();
        saveItem = new javax.swing.JMenuItem();
        saveAsItem = new javax.swing.JMenuItem();
        exitItem = new javax.swing.JMenuItem();
        generateMenu = new javax.swing.JMenu();
        executeMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 65, 92));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 18, 51));

        fileMenu.setForeground(new java.awt.Color(255, 255, 255));
        fileMenu.setText("File");
        fileMenu.setFont(new java.awt.Font("URW Gothic L", 0, 13)); // NOI18N

        newItem.setBackground(new java.awt.Color(0, 18, 51));
        newItem.setFont(new java.awt.Font("URW Gothic L", 0, 13)); // NOI18N
        newItem.setForeground(new java.awt.Color(255, 255, 255));
        newItem.setText("New");
        fileMenu.add(newItem);

        openItem.setBackground(new java.awt.Color(0, 18, 51));
        openItem.setFont(new java.awt.Font("URW Gothic L", 0, 13)); // NOI18N
        openItem.setForeground(new java.awt.Color(255, 255, 255));
        openItem.setText("Open");
        fileMenu.add(openItem);

        saveItem.setBackground(new java.awt.Color(0, 18, 51));
        saveItem.setFont(new java.awt.Font("URW Gothic L", 0, 13)); // NOI18N
        saveItem.setForeground(new java.awt.Color(255, 255, 255));
        saveItem.setText("Save");
        fileMenu.add(saveItem);

        saveAsItem.setBackground(new java.awt.Color(0, 18, 51));
        saveAsItem.setFont(new java.awt.Font("URW Gothic L", 0, 13)); // NOI18N
        saveAsItem.setForeground(new java.awt.Color(255, 255, 255));
        saveAsItem.setText("Save As...");
        fileMenu.add(saveAsItem);

        exitItem.setBackground(new java.awt.Color(0, 18, 51));
        exitItem.setFont(new java.awt.Font("URW Gothic L", 0, 13)); // NOI18N
        exitItem.setForeground(new java.awt.Color(255, 255, 255));
        exitItem.setText("Exit");
        fileMenu.add(exitItem);

        jMenuBar1.add(fileMenu);

        generateMenu.setForeground(new java.awt.Color(255, 255, 255));
        generateMenu.setText("Generate");
        generateMenu.setFont(new java.awt.Font("URW Gothic L", 0, 13)); // NOI18N
        jMenuBar1.add(generateMenu);

        executeMenu.setForeground(new java.awt.Color(255, 255, 255));
        executeMenu.setText("Execute");
        executeMenu.setFont(new java.awt.Font("URW Gothic L", 0, 13)); // NOI18N
        jMenuBar1.add(executeMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu executeMenu;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu generateMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem newItem;
    private javax.swing.JMenuItem openItem;
    private javax.swing.JMenuItem saveAsItem;
    private javax.swing.JMenuItem saveItem;
    // End of variables declaration//GEN-END:variables
}
